server:
  port: 9007
spring:
  application:
    name: question-oa
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://localhost:3306/question?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: s814466057
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:mybatis/mappers/**/*.xml

snowflake:
  workerId: 0
  datacenterId: 1
