server:
  port: 9007
application:
  profile: /home/mengshi/newsimage
  staticAccessPath: /temp/**
spring:
  application:
    name: question-oa
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://localhost:3306/question?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: liuzhirui
    password: l180413L.
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:templates/
    suffix: .html
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:mybatis/mappers/**/*.xml

snowflake:
  workerId: 0
  datacenterId: 1
